import = [
# "~/.config/alacritty/colorschemes/default.toml"
"~/.config/alacritty/colorschemes/catppuccin-frappe.toml"
# "~/.config/alacritty/colorschemes/catppuccin-latte.toml"
# "~/.config/alacritty/colorschemes/catppuccin-macchiato.toml"
# "~/.config/alacritty/colorschemes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "MesloLGM Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 15000

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 8
y = 8

[window.position]
x = 0
y = 0
