[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#eff0eb"
yellow = "#f3f99d"

[colors.cursor]
cursor = "#97979b"

[colors.normal]
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.primary]
background = "#282c34"
foreground = "#eff0eb"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGM Nerd Font Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 15000

[window]
decorations = "buttonless"
decorations_theme_variant = "None"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 8
y = 8

[window.position]
x = 0
y = 0
